---
########################################
########################################
### Repository Configuration as Code ###
########################################
########################################
name: Repository Configuration

########################################
# Start every day at 0600 UTC, and     #
# when this workflow file changes.     #
########################################
on:
  schedule:
    - cron: "0 6 * * *"
  push:
    paths:
      - .github/workflows/repo_config.yml

########################################
# Define the Jobs for this workflow.   #
########################################
jobs:
  apply-config:
    name: Apply .github/repo_config.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Assert Repo Config
        uses: solvaholic/laughing-octo-waffle@add_repo_config
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ADMIN_TOKEN }}
