---
name: Configure Repository

on:
  # Run when the workflow or repo config files change.
  push:
    paths:
      - .github/workflows/repo_config.yml
      - .github/repo_config.json

jobs:
  apply-config:
    name: Apply .github/repo_config.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Assert Repo Config (Dry Run)
        # Dry run when triggered from non-default branch.
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: solvaholic/laughing-octo-waffle@add-topics
        with:
          # dry_run: 'true'
          github_token: ${{ secrets.REPO_ADMIN_TOKEN }}

      - name: Assert Repo Config
        # Assert config when triggered from default branch.
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: solvaholic/laughing-octo-waffle@add-topics
        with:
          github_token: ${{ secrets.REPO_ADMIN_TOKEN }}
